### ISSUE TITLE
How to map indices.pt to csv file?

### ISSUE THREAD

**Issue by Jinhui-Feng** [jsunn-y/ALDE#2]
Hi, I think ALDE should be very useful for the enzyme modification. 
I have a question on prediction. After executed execute_production.py, I got some indices.pt files. How to map these files to a CSV file? Sorry that I'm just a wet lab guy with no concept of machine learning.

**Comment by jsunn-y** [comment]
Hi Jinhui,

"Relevant output will be found in the results path and will end with indices.pt, corresponding to the indices of the training and newly queried variants, in order. These indices can then be mapped to the all_combos.csv file to determine the sequences of the corresponding variants to be further tested." In other words the indices correspond to the rows in all_combos.csv.

Hope this helps!
Jason
