### ISSUE TITLE
Codebase for generating AAindex encodings

### ISSUE THREAD

**Issue by tuln128** [jsunn-y/ALDE#3]
Dear authors,
Thank you very much for such a helpful tool. Regarding different encoding methods mentioned in the article, it seems the function for generating AAindex encodings has not been included in the released codebase (src/encoding_utils.py). Could you please tell me where this function can be retrieved, or how it should be implemented?
Thank you very much in advance.
Kind regards,

**Comment by jsunn-y** [comment]
Thank you for this question. I did not include the AA encoding code here, as I pregenerated most of the embeddings, but you can follow the procedure from the CLADE code. See here: https://github.com/WeilabMSU/CLADE/blob/0ad8bb1781bb56a13478ef5220d1c7fa4d244049/Encoding.py#L43

Hope this help!

**Comment by tuln128** [comment]
> Thank you for this question. I did not include the AA encoding code here, as I pregenerated most of the embeddings, but you can follow the procedure from the CLADE code. See here: https://github.com/WeilabMSU/CLADE/blob/0ad8bb1781bb56a13478ef5220d1c7fa4d244049/Encoding.py#L43
> 
> Hope this help!

Oh, I see. Thank you very much for sharing the link. It's of great help to generate necessary embeddings.
Kind regards,
